#install.packages("SNPassoc");
install.packages("units");
install.packages("ape");
install.packages("poppr");
install.packages("vcfR");
install.packages("RColorBrewer");
install.packages("tidyr");
install.packages("ggplot2");
install.packages("C50")
install.packages("caret")
