install.packages("BiocManager");
BiocManager::install("SNPassoc");
install.packages("units");
install.packages("ape");
install.packages("adegenet");
install.packages("poppr");
install.packages("vcfR");
install.packages("RColorBrewer");
install.packages("tidyr");
install.packages("ggplot2");
install.packages("RWeka")
install.packages("caret")